# Generated by Django 6.0 on 2026-01-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll_no", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=20)),
                ("age", models.IntegerField()),
            ],
        ),
    ]
